#!/usr/bin/env python3
"""
Sky Claims — Ontario MOH Conformance Runner

Runs MCEDT and/or HCV conformance test suites against the MOH conformance endpoints.

Usage:
    python run_conformance.py mcedt             # all 94 MCEDT tests
    python run_conformance.py hcv               # all 20 HCV tests
    python run_conformance.py all               # both
    python run_conformance.py mcedt --test 6.1  # single test
    python run_conformance.py hcv   --test 5.0
    python run_conformance.py mcedt --dry-run   # build envelopes without sending

Prerequisites:
    pip install lxml cryptography requests openpyxl --break-system-packages

Signing key pair (generated by setup):
    mcedt/ebs_signing.key   — keep secret, never commit
    mcedt/ebs_signing.crt   — send to MOH for response encryption

Environment variables (override defaults from MCEDT_HCV conformance emails):
    MCEDT_USERNAME    confsu+382@gmail.com
    MCEDT_PASSWORD    Password22!!
    MCEDT_MOH_ID      616900
    MCEDT_CONF_KEY    a5e64401-fca0-4f68-b777-3f3b1531bd61
    HCV_CONF_KEY      ae1d5821-5d3d-4815-91a3-a0a5391d9492

Results are saved to:
    mcedt/conformance-results/MCEDT_results_YYYYMMDD.xlsx
    hcv/hcv-results/HCV_results_YYYYMMDD.xlsx
"""

import sys
import argparse


def main():
    parser = argparse.ArgumentParser(description="Ontario MOH Conformance Runner")
    parser.add_argument("suite", choices=["mcedt", "hcv", "all"],
                        help="Which conformance suite to run")
    parser.add_argument("--test",    default=None,   help="Run a specific test case ID")
    parser.add_argument("--dry-run", action="store_true", help="Build SOAP without sending")
    args = parser.parse_args()

    if args.suite in ("mcedt", "all"):
        print("=" * 60)
        print("MCEDT Conformance Suite (Ticket #1068818)")
        print("Endpoint: ws.conf.ebs.health.gov.on.ca:1443")
        print("=" * 60)
        from mcedt.conformance_harness import main as mcedt_main
        sys.argv = [sys.argv[0]]
        if args.test:    sys.argv += ["--test", args.test]
        if args.dry_run: sys.argv += ["--dry-run"]
        mcedt_main()

    if args.suite in ("hcv", "all"):
        print("\n" + "=" * 60)
        print("HCV Conformance Suite (Ticket #1068819)")
        print("Endpoint: ws.conf.ebs.health.gov.on.ca:1444")
        print("=" * 60)
        from hcv.conformance_harness import main as hcv_main
        sys.argv = [sys.argv[0]]
        if args.test:    sys.argv += ["--test", args.test]
        if args.dry_run: sys.argv += ["--dry-run"]
        hcv_main()


if __name__ == "__main__":
    main()
